package models

import "gorm.io/gorm"

func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(
		&User{},
		&AdminRole{},
		&RefreshToken{},
		&CreatorProfile{},
		&IP{},
		&Collection{},
		&VideoAssetCollection{},
		&CollectionZip{},
		&VideoAssetCollectionZip{},
		&CollectionDownload{},
		&CollectionFavorite{},
		&CollectionLike{},
		&Emoji{},
		&VideoAssetEmoji{},
		&Tag{},
		&Category{},
		&EmojiTag{},
		&CollectionTag{},
		&Favorite{},
		&Like{},
		&Download{},
		&Report{},
		&AuditLog{},
		&JoinApplication{},
		&HomeDailyStats{},
		&SiteFooterSetting{},
		&RedeemCode{},
		&RedeemCodeRedemption{},
		&CollectionDownloadCode{},
		&CollectionDownloadEntitlement{},
		&CollectionDownloadRedemption{},
		&CollectionDownloadConsumption{},
		&CardTheme{},
		&UploadTask{},
		// New meme social models
		&Meme{},
		&MemeTemplate{},
		&MemePhrase{},
		&UserLike{},
		&UserCollect{},
		&SmsCode{},
		&VideoJob{},
		&VideoJobArtifact{},
		&VideoJobEvent{},
		&VideoJobGIFCandidate{},
		&VideoJobGIFEvaluation{},
		&VideoJobCost{},
		&VideoJobAIUsage{},
		&VideoJobGIFAIProposal{},
		&VideoJobGIFAIReview{},
		&VideoJobGIFAIDirective{},
		&VideoAIPromptTemplate{},
		&VideoAIPromptTemplateAudit{},
		&VideoJobGIFBaseline{},
		&VideoJobGIFRerankLog{},
		&VideoJobGIFManualScore{},
		&ComputeAccount{},
		&ComputeLedger{},
		&ComputePointHold{},
		&VideoQualitySetting{},
		&VideoQualityRolloutAudit{},
		&VideoImageJobPublic{},
		&VideoImageOutputPublic{},
		&VideoImagePackagePublic{},
		&VideoImageEventPublic{},
		&VideoImageFeedbackPublic{},
		&VideoImageQualitySettingPublic{},
		&VideoImageRolloutAuditPublic{},
	)
}
